# Generated by Django 4.0.6 on 2022-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250)),
                ('prenume', models.CharField(max_length=250)),
                ('varsta', models.IntegerField()),
                ('oras', models.CharField(max_length=250)),
            ],
        ),
    ]
